TO-TDAP-426-Update-the-TestOps-readme-page
katalon-studio/katalon-testops pull request #206
Opened 2022-01-26 03:29 UTC by haolekatalon

2022-01-27 09:23 UTC, AntoineTouch requested changes

2022-01-27 09:23 UTC, AntoineTouch commented on README.md
> +**Katalon TestOps** is a web-based application that provides dynamic perspectives and an insightful look at your automation testing data.
TestOps is not just a report generation tool, it is also an orchestration and remote execution tool, so this has to be in the blurb.

2022-01-27 09:23 UTC, AntoineTouch commented on README.md
> +* For community contribution, refer to our [contribution guidelines](CONTRIBUTING.md).
contributions

2022-01-27 09:23 UTC, AntoineTouch commented on README.md
> +* Learn more about orchestration of test automation and DevOps by enrolling in [Katalon Academy](https://academy.katalon.com/#katalon-testops) courses.
about test orchestration and DevOps

2022-01-27 09:23 UTC, AntoineTouch commented on README.md
> +[Katalon Recorder](https://www.katalon.com/katalon-recorder-ide/) is a free and lightweight tool to kickstart test automation from zero without sacrificing the future. It helps you gain confidence in
This can be shortened

2022-01-27 09:37 UTC, AntoineTouch approved these changes

2022-02-02 23:11 UTC, maile-katalon commented on README.md
> +* Maximize testing capacity with remote execution.
With Katalon TestOps, you can:

* Maximize testing capacity with remote execution.
* Analyze and visualize test data in advanced reports and analytics
* Seamlessly integrate with tools, such as Katalon Studio, Katalon TestCloud, and Jira.

2022-02-02 23:12 UTC, maile-katalon commented on README.md
>  * Vote for [Popular Feature Requests](https://github.com/katalon-analytics/katalon-analytics/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request+sort%3Areactions-%2B1-desc).
When you are at it, please remove this line as well as we do not follow that process.

2022-02-02 23:13 UTC, maile-katalon commented on README.md
>  * File a bug in [GitHub Issues](https://github.com/katalon-analytics/katalon-analytics/issues).
Can we instruct them to post a ticket to the support desk instead of GitHub issues? Single source of tracking and response.

2022-02-02 23:14 UTC, maile-katalon commented
Hi @haolekatalon, thank you very much for working on this request. I have added a few comments.
Please let me know if you have any questions.
Thank you.
Mai

2022-02-07 18:57 UTC, maile-katalon commented on README.md
> +* For bug reports, submit a ticket at [Katalon Support](https://support.katalon.com/hc/en-us).
* For bug reports or feature requests, submit a ticket at [Katalon Support](https://support.katalon.com/hc/en-us).

2022-02-08 03:29 UTC, merged